version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=OpenSearch123!@
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - interview-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: interview_user
      POSTGRES_PASSWORD: interview_password
      POSTGRES_DB: interview_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - interview-network

volumes:
  opensearch_data:
  postgres_data:

networks:
  interview-network:
    driver: bridge