spring.application.name=opensearch-template

# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/interview_db
spring.datasource.username=interview_user
spring.datasource.password=interview_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OpenSearch
opensearch.host=localhost
opensearch.port=9200
opensearch.scheme=http
opensearch.username=admin
opensearch.password=OpenSearch123!@
opensearch.index-name=interviews
opensearch.pagination.default-size=10